NCMF\DefaultBundle\Entity\FieldValueText:
    type: entity
    table: "field__value__text"
    repositoryClass: NCMF\DefaultBundle\Repository\FieldValueTextRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        value:
            type: text
            length: 16777215
        description:
            type: string
            length: 255
            nullable: true
    uniqueConstraints:
        instance_field:
            columns: [ instance_id, field_id ]
    manyToOne:
        field:
            targetEntity: ObjectField
            inversedBy: valueText
            joinColumn:
                name: field_id
                referencedColumnName: id
                onDelete: CASCADE
        instance:
            targetEntity: Instance
            inversedBy: valueText
            joinColumn:
                name: instance_id
                referencedColumnName: id
                onDelete: CASCADE
    lifecycleCallbacks: {  }
