NCMF\DefaultBundle\Entity\FieldValueText:
    type: entity
    table: null
    repositoryClass: NCMF\DefaultBundle\Repository\FieldValueTextRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        value:
            type: text
            length: 255
        description:
            type: string
            length: 255
    manyToOne:
        field:
            targetEntity: ObjectField
            inversedBy: valuesText
            joinColumn:
                name: field_id
                referencedColumnName: id
                onDelete: CASCADE
    lifecycleCallbacks: {  }
