NCMF\DefaultBundle\Entity\FieldValueFile:
    type: entity
    table: "field__value__file"
    repositoryClass: NCMF\DefaultBundle\Repository\FieldValueFileRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: text
            length: 255
        description:
            type: string
            length: 255
            nullable: true
    oneToOne:
        file:
            targetEntity: File
            joinColumn:
                name: file_id
                referencedColumnName: id
    manyToOne:
        field:
            targetEntity: ObjectField
            inversedBy: valueFile
            joinColumn:
                name: field_id
                referencedColumnName: id
                onDelete: CASCADE
        instance:
            targetEntity: Instance
            inversedBy: valueFile
            joinColumn:
                name: instance_id
                referencedColumnName: id
                onDelete: CASCADE
    lifecycleCallbacks: {  }
