NCMF\DefaultBundle\Entity\ObjectField:
    type: entity
    table: null
    repositoryClass: NCMF\DefaultBundle\Repository\ObjectFieldRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        code:
            type: string
            length: 255
        type:
            type: string
            length: '20'
    manyToOne:
        object:
            targetEntity: Object
            inversedBy: fields
            joinColumn:
                name: object_id
                referencedColumnName: id
                onDelete: CASCADE
    oneToMany:
        valuesText:
            targetEntity: FieldValueText
            mappedBy: field
            cascade: ["persist"]
    lifecycleCallbacks: {  }
