NCMF\DefaultBundle\Entity\Site:
    type: entity
    table: null
    repositoryClass: NCMF\DefaultBundle\Repository\SiteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        code:
            type: string
            length: 50
        closed:
            type: boolean
    oneToMany:
        aliases:
            targetEntity: SiteAlias
            mappedBy: site
            cascade: ["persist"]
        sections:
            targetEntity: Section
            mappedBy: site
            cascade: ["persist"]
    lifecycleCallbacks: {  }
