<?php

namespace NCMF\DefaultBundle\Repository;

/**
 * FieldValueTextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FieldValueTextRepository extends \Doctrine\ORM\EntityRepository
{
}
