<?php

namespace NCMF\DefaultBundle\Repository;

/**
 * FieldValueFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FieldValueFileRepository extends \Doctrine\ORM\EntityRepository
{
}
