<?php

namespace NCMF\DefaultBundle\Repository;

/**
 * ObjectFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectFieldRepository extends \Doctrine\ORM\EntityRepository
{
}
