<?php

namespace NCMF\DefaultBundle\Repository;

/**
 * SiteAliasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteAliasRepository extends \Doctrine\ORM\EntityRepository
{
}
