# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value


services:
    app.form.registration:
        class: NCMF\DefaultBundle\Form\RegistrationType
        arguments: ['%secret%', "@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: app_user_registration }
    acme_user.password_resetting:
        class: NCMF\DefaultBundle\EventListener\UserRegistrationListener
        arguments: []
        tags:
            - { name: kernel.event_subscriber }

