admin_sitealias_index:
    path:     /
    defaults: { _controller: "NCMFDefaultBundle:SiteAlias:index" }
    methods:  GET

admin_sitealias_show:
    path:     /{id}/show
    defaults: { _controller: "NCMFDefaultBundle:SiteAlias:show" }
    methods:  GET

admin_sitealias_new:
    path:     /new
    defaults: { _controller: "NCMFDefaultBundle:SiteAlias:new" }
    methods:  [GET, POST]

admin_sitealias_edit:
    path:     /{id}/edit
    defaults: { _controller: "NCMFDefaultBundle:SiteAlias:edit" }
    methods:  [GET, POST]

admin_sitealias_delete:
    path:     /{id}/delete
    defaults: { _controller: "NCMFDefaultBundle:SiteAlias:delete" }
    methods:  DELETE
