ncmf_default_homepage:
    path:     /
    defaults: { _controller: NCMFDefaultBundle:Default:index }

ncmf_default_admin_section:
    resource: "@NCMFDefaultBundle/Resources/config/routing/section.yml"
    prefix:   /admin/section

ncmf_default_admin_site:
    resource: "@NCMFDefaultBundle/Resources/config/routing/site.yml"
    prefix:   /admin/site

ncmf_default_admin_sitealias:
    resource: "@NCMFDefaultBundle/Resources/config/routing/sitealias.yml"
    prefix:   /admin/sitealias

ncmf_default_admin_object:
    resource: "@NCMFDefaultBundle/Resources/config/routing/object.yml"
    prefix:   /admin/object

ncmf_default_admin_objectfield:
    resource: "@NCMFDefaultBundle/Resources/config/routing/objectfield.yml"
    prefix:   /admin/objectfield

ncmf_default_admin_fieldvaluetext:
    resource: "@NCMFDefaultBundle/Resources/config/routing/fieldvaluetext.yml"
    prefix:   /admin/fieldvaluetext

ncmf_default_admin_instance:
    resource: "@NCMFDefaultBundle/Resources/config/routing/instance.yml"
    prefix:   /admin/instance





